### PR TITLE
CodeQl issue fixed: Use of password hash with insufficient computational effort

### PR DESCRIPTION
**Pull request by pramit-d**
Changed variable name; 'password' -> 'code'

### CODE REVIEW

**Review by devikasuresh20 — CHANGES_REQUESTED** [review]
Component Name: data-sync-login.component.ts
Issue: Extra symbol "-" inside if condition.

Please correct the below condition : 

if (
                  mmuService !== undefined &&
                  mmuService !== null &&
                  mmuService.length > 0
                  mmuService.length > 0-
                )

**Comment by drtechie** [comment]
The original security issue is here:
https://github.com/PSMRI/MMU-UI/security/code-scanning/4

CodeQL has detected that `password` hashing doesn't have sufficient computational effort.
image


@pramit-d your PR just changes the variable name to something else so that CodeQL doesn't detect the issue.
Please explain how this PR a fix to the root cause.

**Review by drtechie — CHANGES_REQUESTED** [review]
Need explanation on how this PR fixes the root cause.
Same here:
https://github.com/PSMRI/Helpline1097-UI/pull/19

**Comment by NeerajK007** [comment]
@drtechie 

As per integration here, password is getting encrypted(revert possible) at UI and at server it gets decrypted. Another utility at server hash the original password and perform DB operaton.
As per CodelQL, any form of password it is suggesting to hash at first place.

Here we can't hash the password at first place at UI level, because of activity/functions we are doing at our server in API call, "decrypt and then hash"

In this case it becomes a "false positive".

Reason for changing the variable name is to maintain the best practice.
Variable names easily noticeable to outside world is not a safe practice.

I Look forward for your feedback.


** we will provide necessary clarifications going forward with PRs

**Review by NeerajK007 — APPROVED** [review]
OK. Additional char issue resolved.

**Comment by NeerajK007** [comment]
This is a false positive use case and not require any code change.
Closing PR without any merging.

**Pull request closed without merging**
